networks:
  petscare-network:
    driver: bridge

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.insecure=true" 
      - "--providers.docker=true" 
      - "--entrypoints.web.address=:80" 
    ports:
      - "80:80" 
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - petscare-network

  frontend:
    image: node:18-alpine
    container_name: frontend
    restart: always
    build:
      context: ../petscare-frontend
    ports:
      - '3000:3000'
    labels:
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    volumes:
      - ../petscare-frontend:/src/app
    networks:
      - petscare-network

  users-service:
    image: php:8.2-apache
    container_name: users-service
    build:
      context: ../petscare-users-service
    labels:
      - "traefik.http.routers.users.rule=Host(`users.localhost`)"
      - "traefik.http.services.users.loadbalancer.server.port=80"
      - "traefik.http.middlewares.cors.headers.customrequestheaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.cors.headers.customrequestheaders.Access-Control-Allow-Methods=OPTIONS,POST"
      - "traefik.http.middlewares.cors.headers.customrequestheaders.Access-Control-Allow-Headers=*"
    volumes:
      - ../petscare-users-service:/var/www/html
      - ../petscare-users-service/docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      DATABASE_URL: mysql://root:rootpassword@petscare-users:3306/petscare-users
    depends_on:
      - petscare-users
    networks:
      - petscare-network
    command: bash -c "a2ensite 000-default.conf && a2enmod rewrite && composer run-script post-install-cmd && apache2-foreground"

  auth-service:
    image: php:8.2-apache
    container_name: auth-service
    build:
      context: ../petscare-auth-service
    labels:
      - "traefik.http.routers.auth.rule=Host(`auth.localhost`)"
      - "traefik.http.services.auth.loadbalancer.server.port=80"
      - "traefik.http.middlewares.cors.headers.customrequestheaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.cors.headers.customrequestheaders.Access-Control-Allow-Methods=OPTIONS,POST"
      - "traefik.http.middlewares.cors.headers.customrequestheaders.Access-Control-Allow-Headers=*"
    volumes:
      - ../petscare-auth-service:/var/www/html
      - ../petscare-auth-service/docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - petscare-users
    networks:
      - petscare-network
    command: bash -c "a2ensite 000-default.conf && a2enmod rewrite && composer run-script post-install-cmd && apache2-foreground"

  petscare-pets-service:
      image: php:8.2-apache
      container_name: petscare-pets-service
      build:
        context: ../petscare-pets-service
      labels:
      - "traefik.http.routers.pets.rule=Host(`pets.localhost`)"
      - "traefik.http.services.pets.loadbalancer.server.port=80"
      volumes:
        - ../petscare-pets-service:/var/www/html
        - ../petscare-pets-service/docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      environment:
        DATABASE_URL: mysql://root:rootpassword@petscare-pets:3306/petscare-pets
      depends_on:
        - petscare-pets
      networks:
        - petscare-network
      command: bash -c "a2ensite 000-default.conf && a2enmod rewrite && composer run-script post-install-cmd && apache2-foreground"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - petscare-users
    ports:
      - '8081:80'
    environment:
      PMA_HOSTS: petscare-users, petscare-pets
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword 
    networks:
      - petscare-network
    
  petscare-users:
    image: mariadb:latest
    container_name: petscare-users
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpassword
      MYSQL_DATABASE: petscare-users
    volumes:
      - petscare-users-data:/var/lib/mysql
    networks:
      - petscare-network
 
  petscare-pets:
    image: mariadb:latest
    container_name: petscare-pets
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpassword
      MYSQL_DATABASE: petscare-pets
    volumes:
      - petscare-pets-data:/var/lib/mysql
    networks:
      - petscare-network

volumes:
  petscare-users-data:
  petscare-pets-data:
